# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "mutest-tests"
version = "0.0.0"
edition = "2024"

[dependencies]
mutest-exit-code = { path = "../mutest-exit-code" }

cargo_metadata = "0.23"
path-slash = "0.2"
clap = { version = "4", features = ["cargo"] }
serde_json = "1.0"
similar = { version = "3", features = ["inline"] }

[target.'cfg(target_os = "linux")'.dependencies]
mutest-runtime = { path = "../mutest-runtime" }

libc = "0.2"

[lints]
workspace = true
